name: Update Data
on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Update JSON
        run: |
          echo '{ "updated": "'$(date)'" }' > data.json

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Auto-updated data.json" || exit 0
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/sukitha-16/word-storage.git main
