name: Update Data
on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update JSON
        run: |
          echo '{ "updated": "'$(date)'" }' > data.json
        
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Auto-updated data.json"
          git push
